"""Unit tests for adapter.daily_adapt.run — green/yellow/red branches + dry-run."""
from __future__ import annotations

import json
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

import pytest

from src.coach.adapter.daily_adapt import run
from src.coach.adapter.types import AdaptationVerdict
from src.coach.ledger.reader import LedgerReader
from src.coach.ledger.types import AthleteStateRef
from src.coach.ledger.writer import LedgerWriter
from src.coach.periodization.types import SessionType
from src.coach.session_designer.types import DesignedSession


# ---------- shared fixtures ----------

@pytest.fixture
def fixed_now() -> datetime:
    return datetime(2026, 4, 19, 6, 0, tzinfo=timezone.utc)


@pytest.fixture
def now_fn(fixed_now):
    return lambda: fixed_now


@pytest.fixture
def target_date() -> date:
    return date(2026, 4, 19)


@pytest.fixture
def memory_dir(tmp_path) -> Path:
    d = tmp_path / "coach_memory"
    (d / "physiology").mkdir(parents=True)
    (d / "periodization").mkdir(parents=True)
    (d / "reports").mkdir(parents=True)
    (d / "ledger").mkdir(parents=True)
    (d / "physiology" / "cp_w_current.json").write_text(json.dumps({
        "cp_watts": 288, "w_prime_joules": 20000, "athlete_ftp_set": 288,
    }), encoding="utf-8")
    (d / "physiology" / "durability.json").write_text(json.dumps({
        "decay_rate_pct_per_1000kj": {"60s": 1.5, "300s": 2.1},
        "sample_size_rides": 28,
    }), encoding="utf-8")
    (d / "physiology" / "response_profile.json").write_text(json.dumps({
        "types": {"threshold": {"tolerance_class": "high"}},
    }), encoding="utf-8")
    (d / "periodization" / "phase_current.json").write_text(json.dumps({
        "current_phase": "BUILD",
    }), encoding="utf-8")
    return d


@pytest.fixture
def warehouse_dir(tmp_path, target_date) -> Path:
    d = tmp_path / "icu_data_warehouse"
    (d / "2_Wellness").mkdir(parents=True)
    # 28 days of baseline + target day
    history = []
    for i in range(30, 0, -1):
        day = target_date - timedelta(days=i)
        history.append({
            "id": f"{day.isoformat()}T00:00:00",
            "hrv": 68.0,
            "restingHR": 52,
            "sleepSecs": 7 * 3600,
            "soreness": 4,
            "ctl": 70.0, "atl": 75.0,
        })
    history.append({
        "id": f"{target_date.isoformat()}T00:00:00",
        "hrv": 67.0,             # close to baseline → green
        "restingHR": 53,         # +1 vs 52 → green
        "sleepSecs": 7 * 3600,   # 7h → green
        "soreness": 4,           # green
        "ctl": 70.0, "atl": 75.0,
    })
    (d / "2_Wellness" / "wellness_history.json").write_text(
        json.dumps(history), encoding="utf-8")
    return d


def _write_plan(memory_dir: Path, target_date: date, training_type: str = "Aerobic"):
    """Helper: stamp a plan file containing one DayPlanV2 for `target_date`."""
    plan = {
        "week_start": target_date.isoformat(),
        "week_end": (target_date + timedelta(days=6)).isoformat(),
        "focus_theme": "test",
        "weekly_tss_target": 400,
        "coaching_summary": None,
        "days": [{
            "date": target_date.isoformat(),
            "day_of_week": target_date.strftime("%a"),
            "training_type": training_type,
            "icu_type": "Ride" if training_type != "Rest" else "Rest",
            "name": f"Test {training_type} session",
            "description": "Generated by test fixture",
            "duration_min": 90 if training_type != "Rest" else 0,
            "target_tss": 110 if training_type != "Rest" else 0,
            "power_range_w": "200-220",
            "hr_range_bpm": "140-160",
        }],
    }
    (memory_dir / "reports" / f"plan_{target_date.isoformat()}.json").write_text(
        json.dumps(plan), encoding="utf-8")


# ---------- GREEN: no markdown, no proposed, but ledger entry appended ----------

def test_run_green_day_writes_ledger_no_markdown(
    target_date, memory_dir, warehouse_dir, now_fn,
):
    _write_plan(memory_dir, target_date, training_type="Aerobic")
    ledger_path = memory_dir / "ledger" / "decisions.jsonl"
    writer = LedgerWriter(ledger_path)
    reader = LedgerReader(ledger_path)

    result = run(
        target_date=target_date,
        memory_dir=memory_dir, warehouse_dir=warehouse_dir,
        writer=writer, reader=reader, now_fn=now_fn,
        dry_run=False,
    )
    assert result["verdict"] == "green"
    assert result["recommended_action"] == "none"
    assert result["report_path"] is None
    assert result["proposed_session_path"] is None
    assert result["ledger_entry_id"] is not None

    # Ledger has exactly one adaptation_verdict entry
    entries = reader.query(decision_type="adaptation_verdict")
    assert len(entries) == 1
    assert entries[0].payload["verdict"] == "green"
    assert entries[0].payload["recommended_action"] == "none"


# ---------- YELLOW: markdown written, no proposed, ledger appended ----------

def test_run_yellow_day_writes_markdown_only(
    target_date, memory_dir, warehouse_dir, now_fn,
):
    # Override target-day wellness to push HRV into yellow band (-9% vs baseline)
    wh_path = warehouse_dir / "2_Wellness" / "wellness_history.json"
    history = json.loads(wh_path.read_text(encoding="utf-8"))
    history[-1]["hrv"] = 68.0 * 0.91  # ~9% drop → yellow
    history[-1]["sleepSecs"] = 6 * 3600  # 6h → yellow
    wh_path.write_text(json.dumps(history), encoding="utf-8")
    _write_plan(memory_dir, target_date, training_type="Tempo")

    ledger_path = memory_dir / "ledger" / "decisions.jsonl"
    writer = LedgerWriter(ledger_path)
    reader = LedgerReader(ledger_path)

    result = run(
        target_date=target_date,
        memory_dir=memory_dir, warehouse_dir=warehouse_dir,
        writer=writer, reader=reader, now_fn=now_fn,
    )
    assert result["verdict"] == "yellow"
    assert result["recommended_action"] == "nudge_only"
    assert result["report_path"] is not None
    assert result["report_path"].exists()
    assert result["proposed_session_path"] is None

    # markdown contains yellow markers + signal table
    md = result["report_path"].read_text(encoding="utf-8")
    assert ("\U0001f7e1" in md) or ("yellow" in md.lower())
    assert "hrv" in md.lower()


# ---------- RED: markdown + proposed_session.json + ledger ----------

def test_run_red_day_writes_all_three(
    target_date, memory_dir, warehouse_dir, now_fn,
):
    wh_path = warehouse_dir / "2_Wellness" / "wellness_history.json"
    history = json.loads(wh_path.read_text(encoding="utf-8"))
    history[-1]["hrv"] = 68.0 * 0.85       # -15% → red
    history[-1]["restingHR"] = 60          # +8 → red
    history[-1]["sleepSecs"] = 4 * 3600    # 4h → red
    history[-1]["soreness"] = 1            # red
    wh_path.write_text(json.dumps(history), encoding="utf-8")

    _write_plan(memory_dir, target_date, training_type="Threshold")

    ledger_path = memory_dir / "ledger" / "decisions.jsonl"
    writer = LedgerWriter(ledger_path)
    reader = LedgerReader(ledger_path)

    result = run(
        target_date=target_date,
        memory_dir=memory_dir, warehouse_dir=warehouse_dir,
        writer=writer, reader=reader, now_fn=now_fn,
    )
    assert result["verdict"] == "red"
    assert result["recommended_action"] in ("propose_replacement", "rest_48h")
    assert result["report_path"] is not None and result["report_path"].exists()
    assert result["proposed_session_path"] is not None
    assert result["proposed_session_path"].exists()

    # proposed_session.json round-trips into DesignedSession with enum intact
    proposed = DesignedSession.model_validate_json(
        result["proposed_session_path"].read_text(encoding="utf-8"))
    assert proposed.session_type is SessionType.RECOVERY  # threshold → recovery_spin
    assert proposed.date == target_date.isoformat()

    md = result["report_path"].read_text(encoding="utf-8")
    assert "apply_adaptation.py" in md
    assert "--confirm" in md
    assert target_date.isoformat() in md


def test_run_red_day_no_plan_falls_back_to_rest(
    target_date, memory_dir, warehouse_dir, now_fn,
):
    """When no plan_*.json exists, run still produces a red override w/ Rest."""
    wh_path = warehouse_dir / "2_Wellness" / "wellness_history.json"
    history = json.loads(wh_path.read_text(encoding="utf-8"))
    history[-1]["hrv"] = 68.0 * 0.80
    history[-1]["sleepSecs"] = 3 * 3600
    wh_path.write_text(json.dumps(history), encoding="utf-8")
    # NO _write_plan — reports/ stays empty

    ledger_path = memory_dir / "ledger" / "decisions.jsonl"
    writer = LedgerWriter(ledger_path)
    reader = LedgerReader(ledger_path)

    result = run(
        target_date=target_date,
        memory_dir=memory_dir, warehouse_dir=warehouse_dir,
        writer=writer, reader=reader, now_fn=now_fn,
    )
    assert result["verdict"] == "red"
    # Rest passthrough → no proposed_session.json
    assert result["proposed_session_path"] is None
    assert result["report_path"] is not None
    md = result["report_path"].read_text(encoding="utf-8")
    assert "Rest" in md or "rest" in md.lower()


# ---------- DRY-RUN: no writes anywhere ----------

def test_dry_run_skips_all_writes(
    target_date, memory_dir, warehouse_dir, now_fn,
):
    wh_path = warehouse_dir / "2_Wellness" / "wellness_history.json"
    history = json.loads(wh_path.read_text(encoding="utf-8"))
    history[-1]["hrv"] = 68.0 * 0.80     # red
    history[-1]["sleepSecs"] = 3 * 3600
    wh_path.write_text(json.dumps(history), encoding="utf-8")
    _write_plan(memory_dir, target_date, training_type="VO2max")

    ledger_path = memory_dir / "ledger" / "decisions.jsonl"
    writer = LedgerWriter(ledger_path)
    reader = LedgerReader(ledger_path)

    result = run(
        target_date=target_date,
        memory_dir=memory_dir, warehouse_dir=warehouse_dir,
        writer=writer, reader=reader, now_fn=now_fn,
        dry_run=True,
    )
    assert result["verdict"] == "red"
    assert result["report_path"] is None
    assert result["proposed_session_path"] is None
    assert result["ledger_entry_id"] is None

    # ledger file untouched
    assert not ledger_path.exists() or ledger_path.read_text(encoding="utf-8") == ""
    # adapter dir not created or empty
    adapter_dir = memory_dir / "adapter"
    assert (not adapter_dir.exists()) or (list(adapter_dir.iterdir()) == [])


def test_dry_run_idempotent_across_two_calls(
    target_date, memory_dir, warehouse_dir, now_fn,
):
    _write_plan(memory_dir, target_date)
    writer = LedgerWriter(memory_dir / "ledger" / "decisions.jsonl")
    reader = LedgerReader(memory_dir / "ledger" / "decisions.jsonl")

    r1 = run(target_date=target_date, memory_dir=memory_dir,
             warehouse_dir=warehouse_dir, writer=writer, reader=reader,
             now_fn=now_fn, dry_run=True)
    r2 = run(target_date=target_date, memory_dir=memory_dir,
             warehouse_dir=warehouse_dir, writer=writer, reader=reader,
             now_fn=now_fn, dry_run=True)
    assert r1["verdict"] == r2["verdict"]
    assert r1["severity_score"] == r2["severity_score"]
    assert r1["recommended_action"] == r2["recommended_action"]


# ---------- DesignedSession round-trip preserves enum ----------

def test_proposed_session_json_roundtrips_session_type_enum(
    target_date, memory_dir, warehouse_dir, now_fn,
):
    wh_path = warehouse_dir / "2_Wellness" / "wellness_history.json"
    history = json.loads(wh_path.read_text(encoding="utf-8"))
    history[-1]["hrv"] = 68.0 * 0.80
    history[-1]["sleepSecs"] = 3 * 3600
    wh_path.write_text(json.dumps(history), encoding="utf-8")
    _write_plan(memory_dir, target_date, training_type="VO2max")

    writer = LedgerWriter(memory_dir / "ledger" / "decisions.jsonl")
    reader = LedgerReader(memory_dir / "ledger" / "decisions.jsonl")

    result = run(
        target_date=target_date,
        memory_dir=memory_dir, warehouse_dir=warehouse_dir,
        writer=writer, reader=reader, now_fn=now_fn,
    )
    proposed_path = result["proposed_session_path"]
    assert proposed_path is not None

    raw = json.loads(proposed_path.read_text(encoding="utf-8"))
    # Pydantic v2 serializes Enum to its `.value` (Title Case for SessionType,
    # see periodization.types.SessionType — RECOVERY.value == "Recovery").
    assert raw["session_type"] == SessionType.RECOVERY.value

    parsed = DesignedSession.model_validate_json(
        proposed_path.read_text(encoding="utf-8"))
    assert parsed.session_type is SessionType.RECOVERY  # enum identity preserved


# ---------- UTF-8 robustness on non-utf8 default locale ----------

def test_red_markdown_writes_utf8_under_ascii_locale(
    monkeypatch, target_date, memory_dir, warehouse_dir, now_fn,
):
    """Path.write_text must explicitly pass encoding='utf-8' (Chinese chars in template)."""
    wh_path = warehouse_dir / "2_Wellness" / "wellness_history.json"
    history = json.loads(wh_path.read_text(encoding="utf-8"))
    history[-1]["hrv"] = 68.0 * 0.80
    history[-1]["sleepSecs"] = 3 * 3600
    wh_path.write_text(json.dumps(history), encoding="utf-8")
    _write_plan(memory_dir, target_date, training_type="Threshold")

    monkeypatch.setenv("LANG", "C")
    monkeypatch.setenv("LC_ALL", "C")

    writer = LedgerWriter(memory_dir / "ledger" / "decisions.jsonl")
    reader = LedgerReader(memory_dir / "ledger" / "decisions.jsonl")
    result = run(
        target_date=target_date,
        memory_dir=memory_dir, warehouse_dir=warehouse_dir,
        writer=writer, reader=reader, now_fn=now_fn,
    )
    # Read back as bytes; decoding utf-8 must succeed and contain CJK
    raw_bytes = result["report_path"].read_bytes()
    md = raw_bytes.decode("utf-8")
    assert "完全休息" in md or "今日训练" in md or "运行下面的命令" in md


# ---------- Wellness missing → fail-fast ----------

def test_wellness_missing_raises(
    target_date, memory_dir, warehouse_dir, now_fn,
):
    (warehouse_dir / "2_Wellness" / "wellness_history.json").unlink()
    writer = LedgerWriter(memory_dir / "ledger" / "decisions.jsonl")
    reader = LedgerReader(memory_dir / "ledger" / "decisions.jsonl")
    with pytest.raises((FileNotFoundError, ValueError)):
        run(
            target_date=target_date,
            memory_dir=memory_dir, warehouse_dir=warehouse_dir,
            writer=writer, reader=reader, now_fn=now_fn,
        )


def test_wellness_missing_target_date_raises(
    target_date, memory_dir, warehouse_dir, now_fn,
):
    wh_path = warehouse_dir / "2_Wellness" / "wellness_history.json"
    history = json.loads(wh_path.read_text(encoding="utf-8"))
    # remove the target day
    history = [h for h in history if not h["id"].startswith(target_date.isoformat())]
    wh_path.write_text(json.dumps(history), encoding="utf-8")
    writer = LedgerWriter(memory_dir / "ledger" / "decisions.jsonl")
    reader = LedgerReader(memory_dir / "ledger" / "decisions.jsonl")
    with pytest.raises((FileNotFoundError, ValueError)):
        run(
            target_date=target_date,
            memory_dir=memory_dir, warehouse_dir=warehouse_dir,
            writer=writer, reader=reader, now_fn=now_fn,
        )


# ---------- now_fn injection — no datetime.now() in main flow ----------

def test_now_fn_is_used_not_real_clock(
    target_date, memory_dir, warehouse_dir,
):
    """Pass an obviously-wrong now_fn; SignalSnapshot.captured_at must reflect it."""
    weird_now = datetime(2099, 1, 1, 0, 0, tzinfo=timezone.utc)
    _write_plan(memory_dir, target_date)
    writer = LedgerWriter(memory_dir / "ledger" / "decisions.jsonl")
    reader = LedgerReader(memory_dir / "ledger" / "decisions.jsonl")
    result = run(
        target_date=target_date,
        memory_dir=memory_dir, warehouse_dir=warehouse_dir,
        writer=writer, reader=reader,
        now_fn=lambda: weird_now,
    )
    # Acceptance: orchestrator surfaces snapshot.captured_at on its return dict,
    # and that timestamp == weird_now (proving now_fn was the time source for
    # SignalSnapshot construction, not datetime.now()).
    assert result["ledger_entry_id"] is not None
    assert result["captured_at"] == weird_now


# ---------- v3.0.1: real ICU shape (soreness=None) must not crash ----------

def test_run_real_shape_wellness_with_none_subjective(
    target_date, memory_dir, warehouse_dir, now_fn,
):
    """
    Real intervals.icu wellness omits soreness/fatigue/stress for athletes who
    never log them. Adapter must build a SignalSnapshot with soreness_score=None,
    classify it as green, and produce a verdict — not raise ValidationError.
    """
    _write_plan(memory_dir, target_date, training_type="Aerobic")
    wh_path = warehouse_dir / "2_Wellness" / "wellness_history.json"
    history = json.loads(wh_path.read_text(encoding="utf-8"))
    for entry in history:
        entry["soreness"] = None  # mirror real ICU 100%-null shape
    wh_path.write_text(json.dumps(history), encoding="utf-8")

    writer = LedgerWriter(memory_dir / "ledger" / "decisions.jsonl")
    reader = LedgerReader(memory_dir / "ledger" / "decisions.jsonl")
    result = run(
        target_date=target_date,
        memory_dir=memory_dir, warehouse_dir=warehouse_dir,
        writer=writer, reader=reader, now_fn=now_fn,
        dry_run=False,
    )
    # Verdict produced (no crash); soreness silenced as green; ledger written.
    assert result["verdict"] in ("green", "yellow", "red")
    assert result["ledger_entry_id"] is not None
